package main

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
)

func GenerateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + "_permission.pb.go"
	if len(file.Services) == 0 {
		return nil
	}
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	fmt.Print(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-audit. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	return g
}
